import cloth from "@/app/_assets/cloth.svg";

export let products = [
	{
		id: 1,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
		description:
			"This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
	},
	{
		id: 2,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 3,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 4,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 5,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 6,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 7,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 8,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 9,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 10,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 11,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 12,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 13,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 200,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 14,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 15,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 16,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 17,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 18,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 19,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 20,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 21,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 22,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 23,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 24,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 25,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 26,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 27,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 28,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 29,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 30,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
	{
		id: 31,
		src: cloth,
		title: "T-SHIRT WITH TAPE DETAILS",
		rating: "4.5/5",
		price: 120,
		discount: 40,
		rate: 3,
	},
];
